---
- name: Configure gogs
  hosts: app
  become: true
  tasks:
    - name: Create directory
      file:
        path: /mnt/nfs_share/gogs-repositories
        state: directory

    - name: Create custom/conf directory
      file:
        path: /root/gogs/custom/conf
        state: directory
        
    - name: Render app.ini template
      template:
        src: app.ini.j2
        dest: /root/gogs/custom/conf/app.ini