---
- name: Install prerequisite
  hosts: app
  become: true
  tasks:
    - name: Install postgre client
      dnf:
        name: postgresql
        state: present

    - name: Install git
      dnf:
        name: git
        state: present

    - name: Download Gogs archive
      get_url:
        url: https://dl.gogs.io/0.13.0/gogs_0.13.0_linux_amd64.zip
        dest: /tmp/gogs_0.13.0_linux_amd64.zip

    - name: Unpack Gogs archive
      unarchive:
        src: /tmp/gogs_0.13.0_linux_amd64.zip
        dest: /mnt/nfs_share/
        remote_src: yes
    - name: Rename directory
      file:
        src: /mnt/nfs_share/gogs_0.13.0_linux_amd64
        dest: /mnt/nfs_share/gogs
        state: directory
        recurse: yes
    