---
- name: Run gogs
  hosts: app
  become: true
  tasks:     
    - name: Create service file
      template:
        src: gogs.service.j2
        dest: /etc/systemd/system/gogs.service

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start Gogs service
      systemd:
        name: gogs
        state: started
        enabled: yes