---
   
- name: Create service file
  template:
    src: gogs.service.j2
    dest: /etc/systemd/system/gogs.service
    
- name: Disable SELinux enforcement
  command: setenforce 0
  changed_when: false

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Start Gogs service
  systemd:
    name: gogs
    state: started
    enabled: yes