---
- name: Install nfs-utils
  hosts: nfs
  become: true
  tasks:
    - name: Install nfs-utils package
      dnf:
        name: nfs-utils
        state: present

    - name: Enable NFS server service
      systemd:
        name: nfs-server.service
        state: started
        enabled: yes
    

