---
- name: Create directory
  file:
    path: /mnt/nfs_shares
    state: directory

- name: Edit exports
  copy:
    dest: /etc/exports
    content: |
      /mnt/nfs_shares 10.26.0.0/24(rw,sync,no_root_squash)

- name: Execute exportfs command
  become: true
  command:
    cmd: sudo exportfs -arv

- name: Add NFS service to firewall
  become: true
  firewalld:
    service: nfs
    permanent: true
    state: enabled

- name: Add RPC Bind service to firewall
  become: true
  firewalld:
    service: rpc-bind
    permanent: true
    state: enabled

- name: Add Mountd service to firewall
  become: true
  firewalld:
    service: mountd
    permanent: true
    state: enabled

- name: Reload firewall
  become: true
  systemd:
    name: firewalld
    state: restarted

- name: Configure Selinux
  become: true
  seboolean:
    name: nfs_export_all_rw
    set: true
    state: yes
    persistent: true
