- name: Example Play
  hosts: app

  tasks:
    - name: Importing tasks - connect_nfs.yml
      import_tasks: connect_nfs.yml

    - name: Importing tasks - install_prerequisite.yml
      import_tasks: install_prerequisite.yml

    - name: Importing tasks - configure_gogs.yml
      import_tasks: configure_gogs.yml

    - name: Importing tasks - run_gogs.yml
      import_tasks: run_gogs.yml


