---
- name: Install pos
  hosts: db
  become: true
  tasks:
    - name: Install postgresql-server package
      dnf:
        name: postgresql-server
        state: present

    - name: Find out if PostgreSQL is initialized
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data

    - name: Initialize PostgreSQL
      shell: "postgresql-setup initdb"
      when: not postgres_data.stat.exists

    - name: Start and enable services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - postgresql

  handlers:
    - name: Restart PostgreSQL
      service:
        name: postgresql
        state: restarted

